server:
  port: 8088
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    hibernate:
      ddl-auto: none
    open-in-view: false
multitenancy:
  master:
    database: mensis_business
    datasource:
      url: jdbc:postgresql://localhost:5432/mensis_business
      username: root
      password: secret
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-master.yaml
  shard:
    max-tenants: 1
    datasource:
      url-prefix: jdbc:postgresql://localhost:5432/
    liquibase:
      enabled: true
      changeLog: classpath:db/changelog/db.changelog-shard.yaml
      parameters:
        schema: ${spring.jpa.properties.hibernate.default_schema}
        database: ${multitenancy.master.database}
        app_db_user: root
        app_db_password: secret
